Feature/update dto validation
nhnacademy-be7-2joping/2joping-book pull request #57
Opened 2024-11-06 02:47 UTC by Ori-Gui

도서기여자 , 배송관련 API Convention 수행
- dto class를 record로 변경
- dto 변환 방식을 mapstruct 적용
- 도서기여자 Java docs 작성
- test code 수정

*배송관련 java docs 작성필요
*@ValidPathVariable 음수처리 유효성 검사 필요
*배송관련 repository Test는 Order 구현 뒤 작성 필요

mapper 사용시 생기는 target에 mapperImpl 파일에 대한 Test 어떻게 해야하는지 고민

2024-11-06 07:21 UTC, LukaBery commented on src/main/java/com/nhnacademy/bookstore/bookset/contributor/mapper/ContributorMapper.java
> +    @Mapping(source = "contributorRole.name", target = "roleName")
@Mapping 명시를 해야되는지 확인 후 추후 변경 할지 의논해요

2024-11-06 07:24 UTC, LukaBery reviewed
확인했습니다.

2024-11-06 07:26 UTC, 00yuhyun reviewed
코드 확인 완료

2024-11-06 09:21 UTC, Sauter001 requested changes
리뷰 완료

2024-11-06 09:21 UTC, Sauter001 commented on src/main/java/com/nhnacademy/bookstore/bookset/contributor/service/impl/ContributorServiceImpl.java
>                  .orElseThrow(ContributorNotFoundException::new);
비활성화된 기여자도 불러올 거 같습니다

2024-11-06 10:28 UTC, Ori-Gui commented on src/main/java/com/nhnacademy/bookstore/bookset/contributor/mapper/ContributorMapper.java
> +    @Mapping(source = "contributorRole.name", target = "roleName")
@mapping 명시 필요한것만 하도록 수정했습니다!

2024-11-06 10:36 UTC, Ori-Gui commented on src/main/java/com/nhnacademy/bookstore/bookset/contributor/controller/ContributorRoleController.java
> +
NoContent 응답은 도서기여자 역할 삭제 성공시  @ApiResponse 204 이고,
contributorRoleId가 존재하지 않을 경우, contributorRoleService.deleteContributorRole(contributorRoleId) 메서드에서 ContributorRoleNotFoundException 이 발생해 @ApiResponse는 404 입니다

2024-11-06 10:52 UTC, Ori-Gui commented on src/main/java/com/nhnacademy/bookstore/bookset/contributor/service/impl/ContributorServiceImpl.java
>                  .orElseThrow(ContributorNotFoundException::new);
활성화된 기여자만 조회 가능하도록 수정했습니다!

2024-11-07 05:31 UTC, Sauter001 approved these changes

2024-11-07 06:06 UTC, merged